server:
  port: 8761
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  rabbitmq:
    host: mq.tgcloud.net
    port: 5672
    username: admin
    password: admin

logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log