server:
  port: 8010
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active:
      - @profileActive@
      - secure

---
# 不安全配置
spring:
  profiles: insecure
---
# 安全配置 admin登录的用户名和密码
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: admin
  boot:
      admin:
        client:
          #如果Admin端设置了用户名密码访问，你也需要在客户端配置它们
          username: ${spring.security.user.name}       #These two are needed so that the client
          password: ${spring.security.user.password}   #can register at the protected server api
        instance:
          #当前应用程序名字
          name: @pom.artifactId@
          #客户端是否提供本机真实ip
          prefer-ip: true


