server:
  port: 7979
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  datasource:
    username: tiger
    password: 123456
  boot:
    admin:
      client:
        #如果Admin端设置了用户名密码访问，你也需要在客户端配置它们
        username: admin
        password: admin
        instance:
          #当前应用程序名字
          name: @pom.artifactId@
          #客户端是否提供本机真实ip
          prefer-ip: true
  security:
    user:
      name: admin
      password: admin
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
    sampler:
      #默认为0.1；表示调用10次才会上传一次
      probability: 0.1
  #指定zipkin中心 不使用mq需要指定
#  zipkin:
#    base-url: http://zipkin.tgcloud.net:9411

zipkin:
  rabbitmq:
    queue: zipkin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

